version: '3.8'

services:
  moss-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUBLIC_MOSS_BASE_URL=http://localhost:8080
      - ORIGIN=http://localhost:3000
      - AUTH_TRUST_HOST=true
      - AUTH_OIDC_CLIENT_ID=moss-dev
      - AUTH_OIDC_CLIENT_SECRET=z7feqbX7lGyAFzPzGIaC4LT7vidPqrP5
      - AUTH_OIDC_ISSUER=https://auth.dbpedia.org/realms/dbpedia
      - AUTH_OIDC_CLIENT_SCOPE="openid profile email"
      - "httpProxy": "http://proxy.example.com:3128"
      - "httpsProxy": "https://proxy.example.com:3129"
    ports:
      - "5000:3000"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1337:80"
    depends_on:
      - moss-frontend
